name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Build
        run: pnpm run build
      - name: Deploy
        uses: peaceiris/github-pages-deploy-action@v3
        with:
          branch: gh-pages
          folder: dist
