name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18 # You can adjust the Node.js version as needed

    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install

    - name: Build
      run: pnpm run build # Replace with your build script if needed

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Replace with the directory where your built files are located
